### PR TITLE
add upstream / new readmes

### PR DESCRIPTION
**Pull request by BRONSOLO**
@antoinerg @tarzzz, as discussed over Slack, I'm looking to update the branches + flow for our Paketo Buildpack forks. I've included a custom Plotly Readme here: https://github.com/plotly/paketo-buildpacks_cpython/blob/65a0b9fc091edf27eceba3e8250145646a9e7011/README.md. 

The readme-upstream.md was renamed but unchanged.

### CODE REVIEW

**Comment by BRONSOLO** [comment]
(sorry, fixing base)...

**Comment by antoinerg** [comment]
LGTM!

I just have one minor question/suggestion for the README convention. 

Should we leave the upstream `README.md` as is and put our own into `README-plotly.md`? The upside is that we would have one less conflict to resolve when merging upstream. The downside is that `README-plotly.md` won't be rendered by default at the root of the repo in the Github UI. 

Not a big deal but I thought I should bring it up :)

**Comment by BRONSOLO** [comment]
I think having it front and centre is more useful to us (I was weighing both options you described as well ha). Not sure what's best but my feeling resolving any conflicts (by always just fixing upstream readme with a rename) will be easiest!

**Comment by antoinerg** [comment]
> I think having it front and centre is more useful to us (I was weighing both options you described as well ha). Not sure what's best but my feeling resolving any conflicts (by always just fixing upstream readme with a rename) will be easiest!

Perfect! I just wanted to make sure you had considered the other option and that you indeed preferred this one :)

**Comment by antoinerg** [comment]
> (I wish there were a "default" Readme option in github)

I had the same exact thought :D

**Review by antoinerg — APPROVED** [review]

**Pull request merged**
